"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarPlus, CheckCircle2, LoaderCircle, RefreshCw, Search, Settings2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatCurrency, formatDate } from "@/lib/format";

type Status = "AVAILABLE" | "HELD" | "SOLD" | "BLOCKED";
type Rule = { id?: string; name: string; type: string; adjustmentType: string; adjustmentValue: string | number; conditions: Record<string, unknown>; priority: number; enabled: boolean; ticketTypeId: string | null };
type Event = { id: string; name: string; description: string | null; startTime: string; endTime?: string; status: string; venue: { name: string; city: string }; ticketTypes: { id: string; name: string; description?: string | null; basePrice: string | number; quantity: number }[]; inventories: { id?: string; status: Status; currentPrice: string | number; seat?: { rowNumber: number; seatNumber: number; section: { name: string } }; priceHistory?: { id: string; price: string | number; reason: string; createdAt: string }[] }[]; pricingPolicy: { enabled: boolean; minimumPrice: string | number | null; maximumPrice: string | number | null; rules: Rule[] } | null; _count?: { orders: number }; orders?: { id: string; totalAmount: string | number; status: string; createdAt: string; user: { name: string; email: string }; items: unknown[] }[] };
type Dashboard = { organizer: { name: string }; events: Event[] };

async function json(url: string, options?: RequestInit) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Request failed."); return data; }

export function AdminDashboard() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [error, setError] = useState(""); const [active, setActive] = useState<string | null>(null); const [createOpen, setCreateOpen] = useState(false);
  const load = useCallback(async () => { try { setDashboard(await json("/api/admin/dashboard")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load dashboard."); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- initial async request updates state after it resolves.
  useEffect(() => { load(); }, [load]);
  const events = useMemo(() => (dashboard?.events ?? []).filter((event) => (filter === "ALL" || event.status === filter) && `${event.name} ${event.venue.name} ${event.venue.city}`.toLowerCase().includes(query.toLowerCase())), [dashboard, filter, query]);
  const sold = dashboard?.events.reduce((sum, event) => sum + event.inventories.filter((seat) => seat.status === "SOLD").length, 0) ?? 0;
  const revenue = dashboard?.events.reduce((sum, event) => sum + event.inventories.filter((seat) => seat.status === "SOLD").reduce((subtotal, seat) => subtotal + Number(seat.currentPrice), 0), 0) ?? 0;
  if (!dashboard) return <main className="grid min-h-[60vh] place-items-center"><LoaderCircle className="animate-spin text-violet-600" /></main>;
  return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><p className="eyebrow text-violet-600">ORGANIZER WORKSPACE</p><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="mt-2 text-4xl font-extrabold tracking-tight">Manage the whole movie operation.</h1><p className="mt-3 text-slate-500">Showtimes, pricing, seats, reports, and ticket entry in one workspace.</p></div><Button onClick={() => setCreateOpen(true)} className="w-fit bg-violet-600"><CalendarPlus />Create showtime</Button></div><section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Showtimes" value={String(dashboard.events.length)} /><Metric label="Tickets sold" value={String(sold)} /><Metric label="Gross sales" value={formatCurrency(revenue)} /></section><TicketValidator /><section className="mt-10"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="eyebrow text-violet-600">SHOWTIME CONTROL</p><h2 className="mt-1 text-2xl font-extrabold">Your movie lineup</h2></div><div className="flex gap-2"><div className="flex items-center gap-2 rounded-xl border bg-white px-3"><Search className="size-4 text-slate-400" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search" className="h-10 w-36 border-0 p-0 shadow-none focus-visible:ring-0" /></div><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl border bg-white px-3 text-sm"><option value="ALL">All</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="CANCELLED">Cancelled</option></select><Button variant="outline" onClick={load}><RefreshCw />Refresh</Button></div></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 overflow-hidden rounded-3xl border bg-white">{events.map((event) => <EventRow key={event.id} event={event} onManage={setActive} onRefresh={load} />)}{!events.length && <p className="p-10 text-center text-slate-500">No matching showtimes.</p>}</div></section>{createOpen && <CreateShowtime onClose={() => setCreateOpen(false)} onCreated={load} />}{active && <Manager eventId={active} onClose={() => setActive(null)} onRefresh={load} />}</main>;
}

function CreateShowtime({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [minimumStartTime] = useState(() => { const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); return now.toISOString().slice(0, 16); });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await json("/api/admin/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); onClose(); onCreated(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create showtime."); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="relative w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><button type="button" onClick={onClose} aria-label="Close create showtime" className="absolute right-5 top-5 rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X /></button><p className="eyebrow text-violet-600">NEW SHOWTIME</p><h2 className="mt-2 text-2xl font-black">Create a movie showtime</h2><p className="mt-1 text-sm text-slate-500">VIP, Premium, and Classic seating plus starter pricing rules will be created automatically.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input required name="name" placeholder="Movie title" /><Input required name="venueName" placeholder="Cinema name" /><Input required name="city" defaultValue="Bengaluru" placeholder="City" /><Input required name="startTime" type="datetime-local" min={minimumStartTime} /></div><textarea name="description" placeholder="Short movie description" className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm text-slate-950" />{error && <p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy} className="bg-violet-600">{busy && <LoaderCircle className="animate-spin" />}Create showtime</Button></div></form></div>;
}

function EventRow({ event, onManage, onRefresh }: { event: Event; onManage: (id: string) => void; onRefresh: () => void }) { const sold = event.inventories.filter((seat) => seat.status === "SOLD").length; const available = event.inventories.filter((seat) => seat.status === "AVAILABLE").length; const percentage = event.inventories.length ? Math.round(sold / event.inventories.length * 100) : 0; async function status(status: string) { await json(`/api/admin/events/${event.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); onRefresh(); } return <article className="grid gap-4 border-b p-5 last:border-0 md:grid-cols-[1.6fr_1fr_1fr_auto] md:items-center"><div><div className="flex gap-2"><b>{event.name}</b><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-black">{event.status}</span></div><p className="mt-1 text-sm text-slate-500">{formatDate(event.startTime)} · {event.venue.name}, {event.venue.city}</p></div><div><b className="text-sm">{available} available · {sold} sold</b><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${percentage}%` }} /></div><p className="mt-1 text-xs text-slate-500">{percentage}% occupancy</p></div><div><b className="text-sm">{event.pricingPolicy?.enabled ? "Dynamic pricing" : "Base pricing"}</b><p className="mt-1 text-xs text-slate-500">{event._count?.orders ?? 0} orders</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => onManage(event.id)}><Settings2 />Manage</Button>{event.status === "DRAFT" && <Button size="sm" onClick={() => status("PUBLISHED")} className="bg-violet-600">Publish</Button>}{event.status === "PUBLISHED" && <Button size="sm" variant="outline" onClick={() => json("/api/pricing/recalculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventId: event.id }) }).then(onRefresh)}>Price now</Button>}</div></article>; }

function TicketValidator() { const [code, setCode] = useState(""); const [result, setResult] = useState(""); const [ok, setOk] = useState(false); const [busy, setBusy] = useState(false); async function validate(e: FormEvent) { e.preventDefault(); if (busy) return; setBusy(true); setResult(""); try { const data = await json("/api/admin/tickets/validate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketCode: code }) }); setOk(true); setResult(`Checked in ${data.ticket.guest} · ${data.ticket.movie} · ${data.ticket.seat}`); setCode(""); } catch (e) { setOk(false); setResult(e instanceof Error ? e.message : "Could not validate ticket."); } finally { setBusy(false); } } return <section className="mt-8 rounded-3xl border border-violet-100 bg-violet-50 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow text-violet-600">DOOR ENTRY</p><h2 className="mt-1 text-xl font-extrabold">Validate ticket at entry</h2><p className="mt-1 text-sm text-slate-600">Paste the scanned QR value or enter a ticket code.</p></div><form onSubmit={validate} className="flex w-full gap-2 sm:max-w-xl"><Input value={code} onChange={(e) => setCode(e.target.value)} className="h-11 bg-white uppercase" placeholder="MOV-XXXXXXXX or QR value" /><Button disabled={busy} className="h-11 bg-violet-600">{busy ? <LoaderCircle className="animate-spin" /> : <CheckCircle2 />}Check in</Button></form></div>{result && <p role="status" className={`mt-3 rounded-xl p-3 text-sm ${ok ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>{result}</p>}</section>; }

function Manager({ eventId, onClose, onRefresh }: { eventId: string; onClose: () => void; onRefresh: () => void }) { const [event, setEvent] = useState<Event | null>(null); const [tab, setTab] = useState("details"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const load = useCallback(async () => { try { const data = await json(`/api/admin/events/${eventId}/management`); setEvent(data.event); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load showtime."); } }, [eventId]); // eslint-disable-next-line react-hooks/set-state-in-effect -- initial async request updates state after it resolves.
  useEffect(() => { load(); }, [load]); async function save(path: string, body: unknown) { try { setBusy(true); await json(`/api/admin/events/${eventId}${path}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await load(); onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save."); } finally { setBusy(false); } } if (!event) return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60"><LoaderCircle className="animate-spin text-white" /></div>; const sold = event.inventories.filter((seat) => seat.status === "SOLD").length; const revenue = (event.orders ?? []).filter((order) => order.status === "CONFIRMED").reduce((sum, order) => sum + Number(order.totalAmount), 0); return <div className="fixed inset-0 z-50 overflow-auto bg-slate-950/50 p-3 backdrop-blur-sm lg:p-8"><div className="mx-auto max-w-6xl rounded-3xl bg-[#f8f8fc] shadow-2xl"><header className="flex justify-between border-b bg-white p-5"><div><p className="eyebrow text-violet-600">SHOWTIME MANAGER</p><h2 className="mt-1 text-2xl font-black">{event.name}</h2><p className="text-sm text-slate-500">{formatDate(event.startTime)} · {event.venue.name}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X /></button></header><nav className="flex overflow-auto border-b bg-white">{[["details", "Details"], ["tickets", "Ticket types"], ["pricing", "Pricing rules"], ["seats", "Seat control"], ["history", "Sales & history"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-bold ${tab === id ? "border-violet-600 text-violet-700" : "border-transparent text-slate-500"}`}>{label}</button>)}</nav><main className="p-5 lg:p-8"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Occupancy" value={`${event.inventories.length ? Math.round(sold / event.inventories.length * 100) : 0}%`} /><Metric label="Revenue" value={formatCurrency(revenue)} /><Metric label="Orders" value={String(event.orders?.length ?? 0)} /></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{tab === "details" && <Details event={event} busy={busy} save={(body) => save("", body)} />}{tab === "tickets" && <TicketTypes event={event} busy={busy} save={(body) => save("/ticket-types", body)} />}{tab === "pricing" && <Pricing event={event} busy={busy} save={(body) => save("/pricing", body)} />}{tab === "seats" && <Seats event={event} busy={busy} save={(body) => save("/seats", body)} />}{tab === "history" && <History event={event} />}</main></div></div>; }

function Details({ event, busy, save }: { event: Event; busy: boolean; save: (body: unknown) => void }) { const [form, setForm] = useState({ name: event.name, venueName: event.venue.name, city: event.venue.city, description: event.description ?? "", startTime: local(event.startTime) }); return <form onSubmit={(e) => { e.preventDefault(); save(form); }} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 md:grid-cols-2"><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input value={form.venueName} onChange={(e) => setForm({ ...form, venueName: e.target.value })} /><Input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /><Input type="datetime-local" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-24 rounded-xl border p-3 text-sm text-slate-950 md:col-span-2" /><Button disabled={busy} className="w-fit bg-violet-600 md:col-span-2">Save details</Button></form>; }

function TicketTypes({ event, busy, save }: { event: Event; busy: boolean; save: (body: unknown) => void }) { const [types, setTypes] = useState(event.ticketTypes); return <section className="mt-6 rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">Edit seating labels and base prices. Confirmed orders never change.</p>{types.map((type, i) => <div key={type.id} className="mt-3 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3"><Input value={type.name} onChange={(e) => setTypes(types.map((x, n) => n === i ? { ...x, name: e.target.value } : x))} /><Input value={type.description ?? ""} onChange={(e) => setTypes(types.map((x, n) => n === i ? { ...x, description: e.target.value } : x))} placeholder="Description" /><Input type="number" min="0" value={String(type.basePrice)} onChange={(e) => setTypes(types.map((x, n) => n === i ? { ...x, basePrice: e.target.value } : x))} /> </div>)}<Button disabled={busy} onClick={() => save({ ticketTypes: types })} className="mt-4 bg-violet-600">Save ticket types</Button></section>; }

function Pricing({ event, busy, save }: { event: Event; busy: boolean; save: (body: unknown) => void }) { const policy = event.pricingPolicy ?? { enabled: true, minimumPrice: 180, maximumPrice: 800, rules: [] }; const [enabled, setEnabled] = useState(policy.enabled); const [min, setMin] = useState(String(policy.minimumPrice)); const [max, setMax] = useState(String(policy.maximumPrice)); const [rules, setRules] = useState(policy.rules); const patch = (i: number, data: Partial<Rule>) => setRules(rules.map((rule, n) => n === i ? { ...rule, ...data } : rule)); return <section className="mt-6 rounded-2xl bg-white p-5"><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} /> Dynamic pricing enabled</label><div className="mt-3 flex gap-3"><Input type="number" value={min} onChange={(e) => setMin(e.target.value)} placeholder="Minimum" /><Input type="number" value={max} onChange={(e) => setMax(e.target.value)} placeholder="Maximum" /></div>{rules.map((rule, i) => <div key={rule.id ?? i} className="mt-3 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-5"><Input value={rule.name} onChange={(e) => patch(i, { name: e.target.value })} /><select value={rule.type} onChange={(e) => patch(i, { type: e.target.value })} className="rounded-lg border px-2 text-sm"><option value="INVENTORY">Inventory</option><option value="DEMAND">Demand</option><option value="WEEKEND">Weekend</option><option value="EARLY_BIRD">Early bird</option><option value="LAST_MINUTE">Last minute</option><option value="TIME">Time</option></select><select value={rule.adjustmentType} onChange={(e) => patch(i, { adjustmentType: e.target.value })} className="rounded-lg border px-2 text-sm"><option value="PERCENTAGE">Percent</option><option value="FIXED_AMOUNT">Fixed</option><option value="MULTIPLIER">Multiplier</option></select><Input type="number" value={String(rule.adjustmentValue)} onChange={(e) => patch(i, { adjustmentValue: e.target.value })} /><Button variant="ghost" onClick={() => setRules(rules.filter((_, n) => n !== i))} className="text-rose-600">Remove</Button></div>)}<Button variant="outline" onClick={() => setRules([...rules, { name: "New pricing rule", type: "INVENTORY", adjustmentType: "PERCENTAGE", adjustmentValue: 5, conditions: { remainingPercentage: 30 }, priority: 1, enabled: true, ticketTypeId: null }])} className="mt-4">Add rule</Button><Button disabled={busy} onClick={() => save({ enabled, minimumPrice: Number(min), maximumPrice: Number(max), rules })} className="mt-4 ml-2 bg-violet-600">Save pricing</Button></section>; }

function Seats({ event, busy, save }: { event: Event; busy: boolean; save: (body: unknown) => void }) {
  const sections = ["RECLINER", "PRIME", "CLASSIC"];
  return <section className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="border-b bg-slate-50 p-5"><p className="text-sm text-slate-600">Live seat status mirrors the customer view. Admins can block or reopen available seats, but cannot book from this screen.</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-slate-500"><SeatLegend className="border-emerald-500 bg-white text-emerald-700" label="Available" /><SeatLegend className="border-amber-400 bg-amber-100 text-amber-700" label="Held" /><SeatLegend className="border-slate-300 bg-slate-200 text-slate-500" label="Sold" /><SeatLegend className="border-rose-400 bg-rose-100 text-rose-700" label="Blocked" /></div></div><div className="overflow-x-auto px-4 py-8 sm:px-8"><div className="min-w-[620px]"><div className="mx-auto mb-8 max-w-xl rounded-full border-4 border-slate-200 bg-slate-50 py-2 text-center text-xs font-black tracking-[.3em] text-slate-400">SCREEN</div>{sections.map((section) => { const sectionSeats = event.inventories.filter((seat) => seat.seat?.section.name === section); const rows = [...new Set(sectionSeats.map((seat) => seat.seat?.rowNumber ?? 0))]; return <div key={section} className="mt-8"><div className="mb-3 flex items-center justify-between border-b border-slate-100 pb-2"><span className="text-xs font-black tracking-[.15em] text-slate-500">{section} <span className="ml-2 text-violet-600">{formatCurrency(sectionSeats[0]?.currentPrice ?? 0)}</span></span><span className="text-xs text-slate-400">{section === "RECLINER" ? "VIP comfort" : section === "PRIME" ? "Best view" : "Value seats"}</span></div>{rows.map((row) => <div className="mb-2 flex items-center gap-3" key={`${section}-${row}`}><span className="w-4 text-xs font-bold text-slate-400">{section === "RECLINER" ? "J" : String.fromCharCode(65 + row)}</span><div className="grid flex-1 grid-cols-[repeat(14,1fr)] gap-1.5">{sectionSeats.filter((seat) => seat.seat?.rowNumber === row).map((seat) => <button type="button" key={seat.id} disabled={busy || (seat.status !== "AVAILABLE" && seat.status !== "BLOCKED")} onClick={() => save({ inventoryId: seat.id, status: seat.status === "AVAILABLE" ? "BLOCKED" : "AVAILABLE" })} title={`${seat.status} · ${formatCurrency(seat.currentPrice)}${seat.status === "AVAILABLE" || seat.status === "BLOCKED" ? " · Click to toggle block" : ""}`} className={`relative aspect-square rounded-[4px] border text-[9px] font-bold transition sm:text-[10px] ${seat.seat?.seatNumber === 8 ? "mr-6" : ""} ${seat.status === "AVAILABLE" ? "border-emerald-500 bg-white text-emerald-700 hover:bg-emerald-50" : seat.status === "HELD" ? "border-amber-400 bg-amber-100 text-amber-700" : seat.status === "BLOCKED" ? "border-rose-400 bg-rose-100 text-rose-700 hover:bg-rose-200" : "border-slate-300 bg-slate-200 text-slate-500"}`}>{seat.seat?.seatNumber}</button>)}</div></div>)}</div>; })}</div></div></section>;
}

function SeatLegend({ className, label }: { className: string; label: string }) { return <span className="flex items-center gap-2"><i className={`size-3 rounded-sm border ${className}`} />{label}</span>; }

function History({ event }: { event: Event }) { const history = event.inventories.flatMap((seat) => (seat.priceHistory ?? []).map((item) => ({ ...item, seat: seat.seat ? `${String.fromCharCode(65 + seat.seat.rowNumber)}${seat.seat.seatNumber}` : "Seat" }))).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)); return <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5"><h3 className="font-bold">Order history</h3>{event.orders?.map((order) => <div key={order.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{order.user.name}</b><span className="float-right font-bold">{formatCurrency(order.totalAmount)}</span><p className="mt-1 text-xs text-slate-500">{order.user.email} · {formatDate(order.createdAt)} · {order.status}</p></div>)}</section><section className="rounded-2xl bg-white p-5"><h3 className="font-bold">Price history</h3>{history.map((item) => <div key={item.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>{item.seat} · {formatCurrency(item.price)}</b><p className="mt-1 text-xs text-slate-500">{item.reason} · {formatDate(item.createdAt)}</p></div>)}</section></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border bg-white p-5"><p className="text-3xl font-black">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></article>; }
function local(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
