import {
  createHmac,
  randomUUID,
  timingSafeEqual,
} from "crypto";
import { NextResponse } from "next/server";

import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/current-user";

function verifyRazorpaySignature(
  razorpayOrderId: string,
  razorpayPaymentId: string,
  razorpaySignature: string,
) {
  const secret =
    process.env.RAZORPAY_KEY_SECRET;

  if (!secret) {
    throw new Error(
      "RAZORPAY_KEY_SECRET is not configured.",
    );
  }

  const generatedSignature =
    createHmac("sha256", secret)
      .update(
        `${razorpayOrderId}|${razorpayPaymentId}`,
      )
      .digest("hex");

  const generatedBuffer =
    Buffer.from(generatedSignature, "utf8");

  const receivedBuffer =
    Buffer.from(razorpaySignature, "utf8");

  if (
    generatedBuffer.length !==
    receivedBuffer.length
  ) {
    return false;
  }

  return timingSafeEqual(
    generatedBuffer,
    receivedBuffer,
  );
}

export async function POST(request: Request) {
  const user = await getCurrentUser();

  if (!user) {
    return NextResponse.json(
      {
        error:
          "Sign in to complete payment.",
      },
      { status: 401 },
    );
  }

  const body = await request
    .json()
    .catch(() => null);

  const reservationId =
    typeof body?.reservationId === "string"
      ? body.reservationId
      : "";

  const orderId =
    typeof body?.orderId === "string"
      ? body.orderId
      : "";

  const razorpayPaymentId =
    typeof body?.razorpayPaymentId ===
    "string"
      ? body.razorpayPaymentId
      : "";

  const razorpayOrderId =
    typeof body?.razorpayOrderId ===
    "string"
      ? body.razorpayOrderId
      : "";

  const razorpaySignature =
    typeof body?.razorpaySignature ===
    "string"
      ? body.razorpaySignature
      : "";

  if (
    !reservationId ||
    !orderId ||
    !razorpayPaymentId ||
    !razorpayOrderId ||
    !razorpaySignature
  ) {
    return NextResponse.json(
      {
        error:
          "Payment verification details are required.",
      },
      { status: 400 },
    );
  }

  try {
    /*
     * STEP 1
     * Verify the signature generated by Razorpay.
     *
     * This proves that the payment response
     * came from Razorpay and was not modified
     * by the client.
     */
    const signatureValid =
      verifyRazorpaySignature(
        razorpayOrderId,
        razorpayPaymentId,
        razorpaySignature,
      );

    if (!signatureValid) {
      return NextResponse.json(
        {
          error:
            "Payment verification failed.",
        },
        { status: 400 },
      );
    }

    /*
     * STEP 2
     * Perform all database confirmation work
     * inside a Serializable transaction.
     */
    const result =
      await prisma.$transaction(
        async (tx) => {
          /*
           * Find the internal order.
           */
          const order =
            await tx.order.findUnique({
              where: {
                id: orderId,
              },
              include: {
                payment: {
                  include: {
                    attempts: {
                      orderBy: {
                        createdAt: "desc",
                      },
                    },
                  },
                },
                reservation: {
                  include: {
                    items: {
                      include: {
                        ticketInventory: true,
                      },
                    },
                  },
                },
                items: true,
              },
            });

          if (!order) {
            throw new Error(
              "ORDER_NOT_FOUND",
            );
          }

          /*
           * Make sure this order belongs to
           * the currently logged-in user.
           */
          if (order.userId !== user.id) {
            throw new Error(
              "ORDER_NOT_FOUND",
            );
          }

          /*
           * Make sure the order belongs to
           * the reservation sent by the client.
           */
          if (
            order.reservationId !==
            reservationId
          ) {
            throw new Error(
              "INVALID_RESERVATION",
            );
          }

          /*
           * Idempotency:
           *
           * If the payment has already been
           * processed, simply return the
           * existing tickets.
           */
          if (
            order.status === "CONFIRMED"
          ) {
            const existingTickets =
              await tx.ticket.findMany({
                where: {
                  orderItemId: {
                    in: order.items.map(
                      (item) => item.id,
                    ),
                  },
                },
                select: {
                  ticketCode: true,
                },
              });

            return {
              orderId: order.id,
              total:
                order.totalAmount.toNumber(),
              ticketCodes:
                existingTickets.map(
                  (ticket) =>
                    ticket.ticketCode,
                ),
            };
          }

          if (!order.payment) {
            throw new Error(
              "PAYMENT_NOT_FOUND",
            );
          }

          const payment =
            order.payment;

          /*
           * Find the Razorpay payment attempt
           * associated with this order.
           */
          const attempt =
            payment.attempts.find(
              (item) =>
                item.providerOrderId ===
                razorpayOrderId,
            );

          if (!attempt) {
            throw new Error(
              "PAYMENT_ATTEMPT_NOT_FOUND",
            );
          }

          /*
           * Make sure the Razorpay order ID
           * matches the one stored by our server.
           */
          if (
            attempt.providerOrderId !==
            razorpayOrderId
          ) {
            throw new Error(
              "INVALID_RAZORPAY_ORDER",
            );
          }

          /*
           * Make sure the reservation exists.
           */
          const reservation =
            order.reservation;

          if (!reservation) {
            throw new Error(
              "RESERVATION_NOT_FOUND",
            );
          }

          /*
           * Check reservation status.
           */
          if (
            reservation.status !==
            "ACTIVE"
          ) {
            throw new Error(
              "RESERVATION_NOT_ACTIVE",
            );
          }

          /*
           * Check reservation expiration.
           */
          if (
            reservation.expiresAt <
            new Date()
          ) {
            /*
             * Release the seats because
             * the hold has expired.
             */
            await tx.reservation.update({
              where: {
                id: reservation.id,
              },
              data: {
                status: "EXPIRED",
              },
            });

            await tx.ticketInventory.updateMany(
              {
                where: {
                  id: {
                    in: reservation.items.map(
                      (item) =>
                        item.ticketInventoryId,
                    ),
                  },
                  status: "HELD",
                },
                data: {
                  status: "AVAILABLE",
                  version: {
                    increment: 1,
                  },
                },
              },
            );

            throw new Error(
              "RESERVATION_EXPIRED",
            );
          }

          /*
           * Calculate the expected total
           * from the reserved seats.
           */
          const totalAmount =
            reservation.items.reduce(
              (total, item) =>
                total +
                item.ticketInventory.currentPrice.toNumber(),
              0,
            );

          /*
           * Make sure the internal order
           * amount matches the reservation.
           */
          if (
            order.totalAmount.toNumber() !==
            totalAmount
          ) {
            throw new Error(
              "AMOUNT_MISMATCH",
            );
          }

          /*
           * Razorpay orders are created in paise.
           *
           * We compare our rupee amount with
           * the amount stored in the attempt.
           */
          if (
            attempt.amount.toNumber() !==
            totalAmount
          ) {
            throw new Error(
              "AMOUNT_MISMATCH",
            );
          }

          /*
           * STEP 3
           * Mark PaymentAttempt as SUCCESS.
           */
          await tx.paymentAttempt.update({
            where: {
              id: attempt.id,
            },
            data: {
              status: "SUCCESS",
              providerTransactionId:
                razorpayPaymentId,
              failureReason: null,
            },
          });

          /*
           * STEP 4
           * Mark Payment as SUCCESS.
           */
          await tx.payment.update({
            where: {
              id: payment.id,
            },
            data: {
              status: "SUCCESS",
              provider: "RAZORPAY",
              transactionId:
                razorpayPaymentId,
            },
          });

          /*
           * STEP 5
           * Confirm the internal order.
           */
          await tx.order.update({
            where: {
              id: order.id,
            },
            data: {
              status: "CONFIRMED",
            },
          });

          /*
           * STEP 6
           * Complete the reservation.
           */
          await tx.reservation.update({
            where: {
              id: reservation.id,
            },
            data: {
              status: "COMPLETED",
            },
          });

          /*
           * STEP 7
           * Convert HELD seats into SOLD.
           */
          await tx.ticketInventory.updateMany(
            {
              where: {
                id: {
                  in: reservation.items.map(
                    (item) =>
                      item.ticketInventoryId,
                  ),
                },
                status: "HELD",
              },
              data: {
                status: "SOLD",
                version: {
                  increment: 1,
                },
              },
            },
          );

          /*
           * STEP 8
           * Generate tickets.
           */
          for (const item of order.items) {
            await tx.ticket.create({
              data: {
                orderItemId: item.id,
                ticketInventoryId:
                  item.ticketInventoryId,
                ticketCode: `MOV-${randomUUID()
                  .slice(0, 8)
                  .toUpperCase()}`,
              },
            });
          }

          /*
           * STEP 9
           * Create notification.
           */
          await tx.notification.create({
            data: {
              userId: user.id,
              type: "BOOKING_CONFIRMED",
              title:
                "Movie tickets confirmed",
              message: `Your booking for ${reservation.items.length} seat(s) is confirmed.`,
              status: "PENDING",
            },
          });

          /*
           * STEP 10
           * Publish an outbox event.
           *
           * RabbitMQ can consume this event
           * later when we implement the
           * message broker.
           */
          await tx.outboxEvent.create({
            data: {
              eventType:
                "booking.confirmed",
              aggregateType: "Order",
              aggregateId: order.id,
              payload: {
                orderId: order.id,
                userId: user.id,
              },
            },
          });

          /*
           * Retrieve the generated ticket codes.
           */
          const tickets =
            await tx.ticket.findMany({
              where: {
                orderItemId: {
                  in: order.items.map(
                    (item) => item.id,
                  ),
                },
              },
              select: {
                ticketCode: true,
              },
            });

          return {
            orderId: order.id,
            total:
              order.totalAmount.toNumber(),
            ticketCodes:
              tickets.map(
                (ticket) =>
                  ticket.ticketCode,
              ),
          };
        },
        {
          isolationLevel:
            "Serializable",
          maxWait: 5_000,
          timeout: 10_000,
        },
      );

    return NextResponse.json(
      result,
      { status: 200 },
    );
  } catch (error) {
    console.error(
      "Razorpay payment confirmation failed:",
      error,
    );

    if (
      error instanceof Error
    ) {
      switch (error.message) {
        case "ORDER_NOT_FOUND":
          return NextResponse.json(
            {
              error:
                "Order not found.",
            },
            { status: 404 },
          );

        case "INVALID_RESERVATION":
          return NextResponse.json(
            {
              error:
                "Reservation does not match this order.",
            },
            { status: 400 },
          );

        case "PAYMENT_NOT_FOUND":
          return NextResponse.json(
            {
              error:
                "Payment record not found.",
            },
            { status: 400 },
          );

        case "PAYMENT_ATTEMPT_NOT_FOUND":
          return NextResponse.json(
            {
              error:
                "Razorpay payment attempt not found.",
            },
            { status: 400 },
          );

        case "INVALID_RAZORPAY_ORDER":
          return NextResponse.json(
            {
              error:
                "Invalid Razorpay order.",
            },
            { status: 400 },
          );

        case "RESERVATION_NOT_FOUND":
          return NextResponse.json(
            {
              error:
                "Reservation not found.",
            },
            { status: 404 },
          );

        case "RESERVATION_NOT_ACTIVE":
          return NextResponse.json(
            {
              error:
                "This reservation is no longer active.",
            },
            { status: 409 },
          );

        case "RESERVATION_EXPIRED":
          return NextResponse.json(
            {
              error:
                "Your seat hold has expired. Please choose seats again.",
            },
            { status: 409 },
          );

        case "AMOUNT_MISMATCH":
          return NextResponse.json(
            {
              error:
                "Payment amount does not match the reservation.",
            },
            { status: 400 },
          );

        default:
          break;
      }
    }

    return NextResponse.json(
      {
        error:
          "Payment could not be completed.",
      },
      { status: 500 },
    );
  }
}