"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, MapPin, Search, Sparkles, Star } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatDate } from "@/lib/format";

type Movie = { id: string; name: string; description: string | null; startTime: string; venue: { name: string; city: string }; ticketTypes: { basePrice: string | number }[]; inventories: { currentPrice: string | number; status: string }[] };

export function HomePage() {
  const [movies, setMovies] = useState<Movie[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/movies").then((response) => response.ok ? response.json() : { movies: [] }).then((data) => setMovies(data.movies ?? [])).catch(() => setMovies([])).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => movies.filter((movie) => `${movie.name} ${movie.venue.city}`.toLowerCase().includes(query.toLowerCase())), [movies, query]);
  return <main>
    <section className="relative overflow-hidden bg-[#111329] text-white"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="relative mx-auto grid max-w-7xl gap-10 px-5 py-18 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-24"><div className="self-center"><p className="eyebrow text-violet-300"><Sparkles className="mr-2 inline size-4" />YOUR NEXT NIGHT OUT</p><h1 className="mt-4 max-w-3xl text-5xl font-extrabold leading-[.95] tracking-[-.065em] sm:text-7xl">Find the story <span className="text-transparent bg-gradient-to-r from-violet-300 to-fuchsia-300 bg-clip-text">worth leaving home for.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-300">From the best seats in the house to a ticket in your pocket, Showtime makes movie plans feel effortless.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#shows"><Button className="h-11 rounded-xl bg-white px-5 text-slate-950 hover:bg-violet-50">Browse showtimes <ArrowRight /></Button></Link><Link href="#how-it-works"><Button variant="outline" className="h-11 rounded-xl border-white/20 bg-white/5 px-5 text-white hover:bg-white/10 hover:text-white">How it works</Button></Link></div><div className="mt-10 flex flex-wrap gap-7 text-sm"><Metric value="Secure" label="checkout" /><Metric value="Live" label="seat selection" /><Metric value="Fair" label="dynamic pricing" /></div></div><div className="relative min-h-80 overflow-hidden rounded-[2rem] border border-white/15 bg-gradient-to-br from-violet-500 via-fuchsia-500 to-orange-400 p-7 shadow-2xl shadow-violet-950/30"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_18%,rgba(255,255,255,.6),transparent_18%),linear-gradient(150deg,transparent_42%,rgba(17,19,41,.2))]" /><div className="relative flex h-full flex-col justify-between"><span className="w-fit rounded-full border border-white/25 bg-black/15 px-3 py-1 text-xs font-bold tracking-wider backdrop-blur">NOW PLAYING</span><div><p className="text-xs font-bold tracking-[.2em] text-white/70">THE SHOWTIME EDIT</p><p className="mt-2 max-w-xs text-4xl font-black leading-none tracking-[-.06em]">Save the seat. Keep the feeling.</p><div className="mt-5 flex items-center gap-2 text-sm font-bold"><Star className="size-4 fill-amber-300 text-amber-300" />Curated cinema experiences</div></div></div></div></div></section>
    <section id="shows" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-violet-600">IN CINEMAS</p><h2 className="mt-2 text-4xl font-extrabold tracking-[-.055em]">Pick a story. Choose your seat.</h2></div><div className="flex h-11 w-full max-w-sm items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search className="size-4 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a movie or city" className="h-auto border-0 p-0 shadow-none focus-visible:ring-0" /></div></div>
      {loading ? <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-80 animate-pulse rounded-3xl bg-slate-200" />)}</div> : visible.length ? <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((movie, index) => <MovieCard key={movie.id} movie={movie} index={index} />)}</div> : <EmptyShows query={query} />}</section>
    <section id="how-it-works" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="eyebrow text-violet-600">HOW IT WORKS</p><h2 className="mt-2 text-4xl font-extrabold tracking-[-.055em]">The shortest path to a great night.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><Step number="01" title="Find your show" text="Choose a movie, venue, and time that work for your crew." /><Step number="02" title="Claim your seats" text="See live availability and hold up to six seats while you decide." /><Step number="03" title="Tickets, ready" text="Pay securely and keep every ticket together in your account." /></div></div></section>
  </main>;
}

function MovieCard({ movie, index }: { movie: Movie; index: number }) { const prices = movie.inventories.filter((item) => item.status === "AVAILABLE").map((item) => Number(item.currentPrice)); const lowest = prices.length ? Math.min(...prices) : Math.min(...movie.ticketTypes.map((item) => Number(item.basePrice))); const gradients = ["from-[#4f46e5] via-[#7c3aed] to-[#db2777]", "from-[#0f766e] via-[#0891b2] to-[#4f46e5]", "from-[#c2410c] via-[#e11d48] to-[#6d28d9]"]; return <article className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className={`relative h-48 overflow-hidden bg-gradient-to-br ${gradients[index % gradients.length]} p-5`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(255,255,255,.45),transparent_20%)]" /><div className="relative flex h-full flex-col justify-between"><span className="w-fit rounded-full bg-black/20 px-2.5 py-1 text-xs font-bold text-white backdrop-blur">MOVIE</span><p className="max-w-[80%] text-4xl font-black italic tracking-[-.08em] text-white/75">{movie.name.split(" ").map((word) => word[0]).join("")}</p></div></div><div className="p-5"><h3 className="text-xl font-extrabold tracking-tight">{movie.name}</h3><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{movie.description ?? "A big-screen story, waiting for your favorite seat."}</p><div className="mt-4 space-y-2 text-xs font-medium text-slate-500"><p className="flex items-center gap-2"><CalendarDays className="size-4 text-violet-500" />{formatDate(movie.startTime)}</p><p className="flex items-center gap-2"><MapPin className="size-4 text-violet-500" />{movie.venue.name}, {movie.venue.city}</p></div><div className="mt-5 flex items-center justify-between"><span className="text-sm text-slate-500">From <b className="text-slate-950">{formatCurrency(lowest)}</b></span><Link href={`/movies/${movie.id}`}><Button className="rounded-xl bg-violet-600 hover:bg-violet-700">Book <ArrowRight /></Button></Link></div></div></article>; }
function Metric({ value, label }: { value: string; label: string }) { return <span><b className="block text-lg text-white">{value}</b><span className="text-slate-400">{label}</span></span>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-2xl bg-[#f8f8fc] p-6"><span className="text-sm font-black text-violet-600">{number}</span><h3 className="mt-8 text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>; }
function EmptyShows({ query }: { query: string }) { return <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h3 className="text-xl font-extrabold">{query ? "No matching showtimes." : "No published showtimes yet."}</h3><p className="mt-2 text-sm text-slate-500">{query ? "Try a movie title or another city." : "Organizers can create and publish their first movie from the dashboard."}</p>{!query && <Link href="/admin"><Button variant="outline" className="mt-5 rounded-xl">Open organizer dashboard <ArrowRight /></Button></Link>}</div>; }
